name: tparallel
on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: check out
        uses: actions/checkout@v3
      - name: cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: go build ./cmd/tparallel/main.go
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: go test -v ./...
